import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "@/providers";

import "./globals.css";
import { Header } from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Header />
          <div className="overflow-hidden">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
